# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 6
#$ -q mThM.q
#$ -l mres=60G,h_data=10G,h_vmem=10G,himem
#$ -cwd
#$ -j y
#$ -N growth_phenology
#$ -o growth_phenology.log
#$ -m bea
#$ -M KimAY@si.edu
#
# ----------------Modules------------------------- #
module load bioinformatics/R
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
git checkout master
Rscript -e 'source("RScripts/Pheno_tsensitivity_figure_tmax.R")'
Rscript -e 'source("RScripts/Pheno_tsensitivity_figure_april_april_tmax.R")'
git add -A
git commit -m "master results"
git push
#
git checkout 2.5_cam
Rscript -e 'source("RScripts/Pheno_tsensitivity_figure_tmax.R")'
Rscript -e 'source("RScripts/Pheno_tsensitivity_figure_april_april_tmax.R")'
git add -A
git commit -m "2.5sd results"
git push
#
git checkout 3_cam
Rscript -e 'source("RScripts/Pheno_tsensitivity_figure_tmax.R")'
Rscript -e 'source("RScripts/Pheno_tsensitivity_figure_april_april_tmax.R")'
git add -A
git commit -m "3sd results"
git push
#
echo = `date` job $JOB_NAME done
