---
title: ''
author: ''
output:
  pdf_document:
    citation_package: natbib
    fig_caption: yes
  html_document:
    df_print: paged
bibliography: null
biblio-style: apalike
csl: new-phytologist.csl
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage{xcolor}
---
```{r, Table HF_bands_bySP, eval=TRUE, echo=FALSE, message=FALSE}
library(knitr)
library(kableExtra)
table <- read.csv("tables_figures/HF_bands_bySP.csv",stringsAsFactors = FALSE, check.names = FALSE)
kbl(table, format = "latex", booktabs = T)
```

\newpage
```{r, Table SCBI_bands_bySP, eval=TRUE, echo=FALSE, message=FALSE}
library(knitr)
library(kableExtra)
table <- read.csv("tables_figures/SCBI_bands_bySP.csv",stringsAsFactors = FALSE, check.names = FALSE)
kbl(table, format = "latex", booktabs = T)
```

\newpage
```{r, Table sample_size_by_year, eval=TRUE, echo=FALSE, message=FALSE}
library(knitr)
library(kableExtra)
table <- read.csv("tables_figures/sample_size_by_year.csv",stringsAsFactors = FALSE, check.names = FALSE)
kbl(table, format = "latex", booktabs = T)
```
