---
title: ""
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

November 19, 2021
\newline
\newline

Dear Editor:

We are pleased to submit our manuscript "Warmer spring temperatures in temperate deciduous forests advance the timing of tree growth but have little effect on annual woody productivity", by Cameron Dow and co-authors, for consideration for publication in *Nature*. 

As the climate warms, it is generally expected that temperate deciduous forests, which accounts for ~30% of the global forest carbon sink, will increase their carbon dioxide (CO~2~) sequestration due to lengthened growing seasons. 
This expectation is based on observations that warm springs result in earlier leaf-out and commencement of net CO~2~ uptake; however, little is known about how spring temperatures affect tree stem growth, which sequesters carbon in wood that has a long residence time in the ecosystem.
In fact, we are aware of only one study that has documented stem-growth phenology of temperate deciduous forests over multiple years (and this one did not consider the influence of spring temperatures on phenology).
Here, using dendrometer band measurements from 463 trees across two forests, we show that warmer spring temperatures shifted the woody growth of deciduous trees earlier but had no consistent effect on peak growing season length, maximum daily growth rates, or annual growth. 
We confirmed the latter finding on the centennial scale using 207 tree-ring chronologies from 108 forests across eastern North America, where annual growth was far sensitive to temperatures during the peak growing season but not to spring temperatures. 
Our findings imply that extra CO~2~ uptake in years with warmer springs is not allocated to long-lived woody biomass, where it could have a substantial and lasting impact on the forest C balance.
Rather, contradicting current projections from global C cycle models, our empirical results imply that warming spring temperatures are unlikely to increase the woody productivity or strengthen the CO~2~ sink of temperate deciduous forests.
In short, our findings imply that the potential for temperate deciduous forests to mitigate the climate crisis is probably over-estimated.
This is a significant finding that will be of interest to the broad readership of *Nature*.

We believe our manuscript to be an appropriate length for *Nature*, with 2,597 words, 3 display items, and 48 references in the main article. The article is accompanied by an Extended Data file (3 tables, 7 figures) and a supplementary table.

Thank you for considering our submission for *Nature*.  

Sincerely,
\newline
\newline
    
Kristina Anderson-Teixeira, on behalf of all co-authors.
