---
title: " "

output: 
  pdf_document:
    fig_caption: yes

header-includes:  \usepackage{float}
                  \usepackage{caption}
                  \captionsetup[table]{font=footnotesize}
                  \captionsetup[figure]{font=footnotesize}
                  \captionsetup[figure]{labelformat=empty}
                  \captionsetup[table]{labelformat=empty}


---

```{r, include=FALSE}
options(tinytex.verbose = TRUE)
options(knitr.table.format = "latex")
```

```{r eval = TRUE, echo=FALSE, warning=FALSE}
library(knitr)
library(kableExtra)
hypothesis_table <- read.csv(file = "hypothesis_table.csv", stringsAsFactors = FALSE, check.names = FALSE)

#add footnote markers:
hypothesis_table[8,2] <- paste0(hypothesis_table[8,2], footnote_marker_number(1)) 
hypothesis_table[8,3] <- paste0(hypothesis_table[8,3], footnote_marker_number(2)) 
hypothesis_table[8,5] <- paste0(hypothesis_table[8,5], footnote_marker_number(3)) 

kable(hypothesis_table, col.names = c("Hypotheses and Specific Predictions", "RP", "DP","RP", "DP", "Results"), caption = "Table 1. Table of hypotheses and associated specific predictions, whether each was supported ('yes'; signficant at p<0.05), rejected ('no'; opposite trend signficant at p<0.05), or found insigificant ('n.s.'; no significant correlation), and display items showing the results. 'RP' and 'DP' refer to ring- and diffuse- porous species, respectively.", format = "latex", booktabs = TRUE,  escape = F)%>%
  #column_spec(1, width = "4cm") %>%
  add_header_above(c(" ", "SCBI" = 2, "Harvard Forest"=2, " " )) %>%
  pack_rows("Warmer early springs result in earlier stem growth and longer growing seasons", 1, 5, latex_gap_space = "1em", colnum = 4, hline_before = FALSE) %>%
  pack_rows("Maximum growth rates are independent of early spring temperatures.", 6, 6, latex_gap_space = "1em", colnum = 4, hline_before = FALSE) %>%
  pack_rows("Annual stem growth responds positively to warmer spring temperatures.", 7, 8, latex_gap_space = "1em", colnum = 4, hline_before = FALSE) %>%
  kable_styling(latex_options = c("scale_down", "hold_position"), protect_latex = T) %>%

#add footnote: 
kableExtra::footnote(number = c("One of nine species analyzed had significant positive response to April $T_{max}$; one had significant negative response to March $T_{max}$", "One of two species analyzed had signficant positive response to April $T_{max}$, both had negative response to May $T_{max}$", "The one species analyzed had a signficant negative response to April $T_{max}$."), footnote_as_chunk = FALSE, threeparttable=TRUE, escape = FALSE)
```

\newpage
```{r species_table, eval=TRUE, echo=FALSE, warning=FALSE}
library(knitr)
library(kableExtra)
species_table <- read.csv(file = "species_table.csv", col.names = c("site", "xylem porosity","species", "species code", "n trees", "n tree-years", "n cores", "date range"),  stringsAsFactors = FALSE, check.names = FALSE)
kable(species_table, caption = "Table 2. Dominant ring- and diffuse-porous species at SCBI and Harvard Forest analyzed here, along with sample sizes.",  format = "latex", booktabs = TRUE,  escape = F) %>%
add_header_above(c(" ", " ", " ", " ", "dendrometer bands" = 2, "tree cores"=2 )) %>%
kable_styling(latex_options = c("scale_down", "hold_position"), protect_latex = T) 
```

\newpage
```{r mean_growth_parameters_table,  eval=TRUE, echo=FALSE, warning=FALSE}
library(knitr)
library(kableExtra)
mean_growth_parameters <- read.csv("mean_growth_parameters.csv",  col.names = c("", "ring","diffuse","ring", "diffuse"), stringsAsFactors = FALSE, check.names = FALSE)
kable(mean_growth_parameters, caption = "Table 3. Summary of parameters describing the phenology and rate of growth for ring- and diffuse- porous species at SCBI and Harvard Forest. ",  format = "latex", booktabs = TRUE,  escape = F) %>%
add_header_above(c(" ",  "SCBI" = 2, "Harvard Forest"=2 )) %>%
    column_spec(1, width = "4cm") %>%
kable_styling(latex_options = c("scale_down", "hold_position"), protect_latex = T) 
```
