---
title: ""
author:
output: 
  pdf_document:
    fig_caption: yes
    #toc: true # table of content true
    #toc_depth: 2  
header-includes:  \usepackage{float}
                  \usepackage{caption}
                  \captionsetup[figure]{labelformat=empty}
                  \captionsetup[table]{labelformat=empty}
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

![**Figure 3 | Sensitivity of annual growth, as derived from tree-rings, to monthly mean maximum temperatures (*T~max~*), for 207 chronologies from 108 sites across eastern North America**. Colors indicate the correlation between monthly *T~max~* and a dimensionless ring width index (RWI) derived from the multiple trees that form each chronology and emphasizing interannual variability associated with climate. Chronologies are grouped by xylem porosity and ordered by mean April *T~max~*. Plots are annotated to highlight records from our two focal sites, the Smithsonian Conservation Biology Institute (SCBI) and Harvard Forest (HF; Extended Data Table 1). Sites included are mapped in Extended Data Figure 1, species analyzed and numbers of significant correlations to *T~max~* are summarized in `Extended Data Table 3, and chronology details are given in SI Table 1.](tmax_quiltplots.jpg){ width=100% }
