---
title: "Cover letter"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Dear Anna Armstrong:

We are pleased to provide a revised version of Nature manuscript 2021-11-18307A, now entitled "Warm springs alter timing but not total growth of temperate deciduous trees".

We have made the following minor revisions to the manuscript and associated materials:


- changed the title to one meeting the length constraints
- responded to all reviewer comments, as detailed in our Response to Reviews (no major changes required)
- responded to all editorial comments in the email and editorial request form (no major changes required)
- archived all raw tree-ring data to the GitHub repository
- created a new Zenodo release, and provided Zenodo DOI in the required locations
- provided a supplementary information guide
- completed all related manuscript forms
- provided potential cover images

We hope that you will find all materials acceptable for publication, and will be happy to address any required revisions.

Best regards,

Kristina Anderson-Teixeira (on behalf of full author team)